### ISSUE TITLE
infra: Separate Bootstrap nodes from Relay nodes

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#383]
Now that we have browser support, we want to make sure that we can scale the relay and boostrap nodes that we and others host independently from one another. And that the bootstrap nodes don't get impacted by also being responsible for handling relay requests.

**Comment by opaolini** [comment]
We have the following relayer nodes are running on Digital Ocean:
```
eu-relayer-node-1:
  host: 157.230.112.64
us-relayer-node-1:
  host: 167.172.201.142
ap-relayer-node-1:
  host: 159.65.4.82
```

They can be scaled separately.

We should disable relaying for our bootstrap nodes, and upgrade the version that's running there to the newest release version.
